### PR TITLE
feat: automatically determine display version for XPlanung schemas

### PR DESCRIPTION
**Pull request by florianesser**
Replaces the static display versions array by a dynamic method to determine the display version from the XSD to be downloaded.

### CODE REVIEW

**Review by stempler — APPROVED** [review]
LGTM, in the build it seems though that this does not lead to any changes, in case that was desired.
See summary: https://github.com/wetransform/offline-resources/actions/runs/9187612089?pr=70

**Comment by florianesser** [comment]
> in the build it seems though that this does not lead to any changes, in case that was desired.

When I tested this locally, the schema version of the XPlanung 6.0 changed to `6.0.2` (was `6.0` before this change). image

I don't think that this can be seen in the build output as the generated jars are not kept.

**Comment by stempler** [comment]
@florianesser If the resulting changes are not checked in then you would need to also change the [metadata file](https://github.com/wetransform/offline-resources/blob/master/resources/hosts/repository.gdi-de.org/.metadata/metadata.yml) to a new version to force creating a new version.

**Comment by florianesser** [comment]
> If the resulting changes are not checked in then you would need to also change the [metadata file](https://github.com/wetransform/offline-resources/blob/master/resources/hosts/repository.gdi-de.org/.metadata/metadata.yml) to a new version to force creating a new version.

Thanks a lot for the hint! I updated the metadata file now.

**Pull request merged**
